packages:
  - "packages/*"
catalog:
  "@tsconfig/node-ts": ^23.6.1
  "@tsconfig/node20": ^20.1.5
  "@types/lodash-es": "^4.17.12"
  "@types/node": ^22.13.11
  "@apidevtools/json-schema-ref-parser": "^12.0.1"
  del-cli: ^6.0.0
  lerna: ^8.2.1
  typescript: ^5.8.3
  payload-is: "^0.1.6"
  lodash-es: "^4.17.21"
  openapi-types: "^12.1.3"
  ajv: "^8.17.1"
  undici-types: "^7.8.0"